language: php

php:
  - 7.1
  - 7.2

sudo: false

before_install:
  - composer self-update
  - mkdir build

install:
  - travis_retry composer install --no-interaction --prefer-source

script:
  - ./bin/phpunit

notifications:
  webhooks:
    on_success: always
    on_failure: always
    on_start: false
